#!/usr/bin/env sh
echo \> RISG_CLI=y RISG_BIGINT=y pnpm vite build >&2
RISG_CLI=y RISG_BIGINT=y pnpm vite build >&2 || exit 1

file='build/cli/index.js'

echo \> node "$file" "$@" >&2
node --enable-source-maps "$file" "$@"
